name: 🐛 Bug Report
description: Report a bug or unexpected behavior in MineraLog
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form completely.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I do X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The app should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the app...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of MineraLog are you using?
      placeholder: e.g., 1.5.0
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: e.g., Pixel 6, Samsung Galaxy S23
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android?
      placeholder: e.g., Android 14, API 34
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logcat Output
      description: If applicable, paste relevant logcat output here
      placeholder: Paste logcat here (use adb logcat)
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots or screen recordings
      placeholder: Drag and drop images/videos here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the problem
      placeholder: |
        - Does this happen consistently or intermittently?
        - Did this work in a previous version?
        - Any other relevant details...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of MineraLog
          required: false
        - label: I have included logcat output (if applicable)
          required: false
